version: '3.8'

services:
  authentication:
    image: authentication:latest
    container_name: authentication
    env_file:
      - .env
    networks:
      - internal-network

networks:
  internal-network:
    external: true
